"""
director.py — inject events into a running simulation, and every agent
remembers it and can react on their next tick. This is the "God's-eye
view" feature from MiroFish we talked about: you're not scripting any
individual agent's reaction, you're just dropping a fact into the world
and letting personality + memory take it from there.

Usage (from a shell, while tick_engine.py is running or paused):
    python3 -c "
    from director import inject_event
    inject_event('A mass casualty event just arrived — a bus crash with 12 injured.')
    "

Works on any system generated by meta_builder.py, since it only depends
on agents.json and memory.py's AgentMemoryStore — no theme-specific code.
"""

import json
import os
import time

from memory import AgentMemoryStore

AGENTS_PATH = "agents.json"
EVENT_LOG_PATH = "event_log.json"
EVENT_IMPORTANCE = 10  # max weight, so this dominates memory retrieval on the next tick


def _load_agents():
    with open(AGENTS_PATH, "r") as f:
        return json.load(f)["agents"]


def _current_tick():
    """Infers the current tick from the last entry in event_log.json, so
    the injected event lands at 'now' rather than at tick 0. Falls back to
    tick 0 if the simulation hasn't run yet."""
    if not os.path.exists(EVENT_LOG_PATH):
        return 0
    with open(EVENT_LOG_PATH, "r") as f:
        log = json.load(f)
    if not log:
        return 0
    last = log[-1]
    return last.get("day", 0) * 24 + last.get("hour", 0)


def inject_event(event_text, tick=None):
    """
    Drops a world event into the simulation:
    - Logged to event_log.json (shows up in viewer.py, tagged distinctly)
    - Added as a high-importance memory to EVERY agent, so it surfaces on
      their next tick's memory retrieval regardless of relevance scoring

    Returns how many agents received the event.
    """
    agents = _load_agents()
    current_tick = tick if tick is not None else _current_tick()

    for agent in agents:
        store = AgentMemoryStore(agent["id"])
        store.add(text=f"[WORLD EVENT] {event_text}", tick=current_tick, importance=EVENT_IMPORTANCE)

    # Log it visibly in the event feed too, tagged so the viewer can style it differently
    log = []
    if os.path.exists(EVENT_LOG_PATH):
        with open(EVENT_LOG_PATH, "r") as f:
            log = json.load(f)
    day, hour = divmod(current_tick, 24)
    log.append({
        "day": day, "hour": hour, "agent": "WORLD EVENT",
        "text": event_text, "logged_at": time.time(),
    })
    with open(EVENT_LOG_PATH, "w") as f:
        json.dump(log, f, indent=2)

    return f"Event injected at Day {day} {hour:02d}:00, delivered to {len(agents)} agents. " \
           f"They'll react starting their next tick."


def inject_event_for_agent(agent_id, event_text, tick=None):
    """Same as inject_event, but targeted at a single agent — useful for
    a personal event ('you just got a call from your sister') rather than
    something the whole world would know about."""
    agents = _load_agents()
    if not any(a["id"] == agent_id for a in agents):
        return f"ERROR: no agent with id '{agent_id}' found in {AGENTS_PATH}."

    current_tick = tick if tick is not None else _current_tick()
    store = AgentMemoryStore(agent_id)
    store.add(text=f"[PERSONAL EVENT] {event_text}", tick=current_tick, importance=EVENT_IMPORTANCE)
    return f"Personal event delivered to '{agent_id}' at tick {current_tick}."
