"""mdfile1.py – Tool to update and store full information about the coding agent.

This module provides a single public function ``generate_full_info`` which gathers the
most important documentation files of the project (the agent overview, the README‑style
documentation, and the CLI source) and writes a consolidated markdown file
``agent_full_info.md``.  The function can be called from the command line or imported
by other scripts.

Usage::

    python mdfile1.py               # writes ``agent_full_info.md`` in the repo root
    python mdfile1.py output.md      # writes to ``output.md`` instead of the default

The implementation is deliberately simple – it reads a predefined list of source
files, inserts a header for each, and dumps the raw file contents inside fenced
markdown code blocks.  If a file cannot be read (e.g. binary or missing) a short
error note is written instead of raising an exception, so the tool is robust when
run in different environments.
"""

import sys
import pathlib
from typing import Iterable, List

# ---------------------------------------------------------------------------
# Configuration – which files constitute the "full information" about the
# agent.  Adjust this list if you add new documentation files.
# ---------------------------------------------------------------------------
DEFAULT_FILES: List[pathlib.Path] = [
    pathlib.Path("AGENT_OVERVIEW.md"),
    pathlib.Path("DOCUMENTATION.md"),
    pathlib.Path("cli.py"),
    pathlib.Path("agent.py"),
    pathlib.Path("tools.py"),
    pathlib.Path("vision_tools.py"),
]


def _read_file(path: pathlib.Path) -> str:
    """Return the text contents of *path*.

    If the file cannot be opened, a short placeholder string is returned so the
    caller can continue processing the remaining files.
    """
    try:
        return path.read_text(encoding="utf-8")
    except Exception as exc:  # pragma: no cover – defensive, not expected
        return f"[Error reading {path}: {exc}]"


def generate_full_info(
    output_path: pathlib.Path = pathlib.Path("agent_full_info.md"),
    source_files: Iterable[pathlib.Path] = DEFAULT_FILES,
) -> None:
    """Write a markdown file that aggregates the contents of *source_files*.

    The resulting markdown has the following structure::

        # Agent Full Information

        ## <relative path>
        ```
        <file contents>
        ```

        ...repeat for each source file...

    Parameters
    ----------
    output_path:
        Where to write the aggregated markdown.  Parent directories are created
        automatically if they do not exist.
    source_files:
        An iterable of ``pathlib.Path`` objects (or strings) pointing at the
        files to include.  Paths are resolved relative to the current working
        directory.
    """
    output_path = pathlib.Path(output_path)
    # Ensure the parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as out:
        out.write("# Agent Full Information\n\n")
        out.write(
            "This document aggregates the most important source and documentation \n"
            "files for the coding‑agent project.  It is generated by ``mdfile1.py``.\n\n"
        )
        for file_path in source_files:
            p = pathlib.Path(file_path)
            # Resolve to a relative path for nicer headings
            rel = p.as_posix()
            out.write(f"## {rel}\n")
            out.write("```\n")
            out.write(_read_file(p))
            out.write("\n```\n\n")
    print(f"✅ Generated {output_path}")


def _cli(argv: List[str] | None = None) -> None:
    """Simple command‑line entry point.

    ``argv`` mimics ``sys.argv[1:]``; if omitted the real ``sys.argv`` is used.
    ``mdfile1.py <output_path>`` writes to the supplied output file, otherwise the
    default ``agent_full_info.md`` is used.
    """
    if argv is None:
        argv = sys.argv[1:]
    if argv:
        out = pathlib.Path(argv[0])
    else:
        out = pathlib.Path("agent_full_info.md")
    generate_full_info(out)


if __name__ == "__main__":  # pragma: no cover – manual execution
    _cli()
