"""
memory.py — per-agent memory storage, generated by meta_builder.py.

Same design as the original town sim: recency + importance + relevance
blended for retrieval. No embeddings needed here — cheap and good enough
for a tick-based simulation where "importance" already does most of the
work of surfacing what matters.
"""

import json
import math
import os
import time
from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass
class Memory:
    text: str
    tick: int
    importance: int = 5
    embedding: Optional[list] = None
    created_at: float = field(default_factory=time.time)


class AgentMemoryStore:
    def __init__(self, agent_id: str, storage_dir: str = "memories"):
        self.agent_id = agent_id
        self.storage_dir = storage_dir
        os.makedirs(storage_dir, exist_ok=True)
        self.path = os.path.join(storage_dir, f"{agent_id}.json")
        self.memories: list[Memory] = self._load()

    def _load(self) -> list[Memory]:
        if not os.path.exists(self.path):
            return []
        with open(self.path, "r") as f:
            raw = json.load(f)
        return [Memory(**m) for m in raw]

    def save(self):
        with open(self.path, "w") as f:
            json.dump([asdict(m) for m in self.memories], f, indent=2)

    def add(self, text: str, tick: int, importance: int = 5, embedding=None):
        mem = Memory(text=text, tick=tick, importance=importance, embedding=embedding)
        self.memories.append(mem)
        self.save()
        return mem

    def retrieve_relevant(self, current_tick: int, query_embedding=None, top_k: int = 5):
        if not self.memories:
            return []
        scored = []
        for mem in self.memories:
            recency_score = math.exp(-0.01 * max(0, current_tick - mem.tick))
            importance_score = mem.importance / 10.0
            relevance_score = 0.5
            if query_embedding is not None and mem.embedding is not None:
                relevance_score = _cosine_similarity(query_embedding, mem.embedding)
            total = recency_score + importance_score + relevance_score
            scored.append((total, mem))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [mem for _, mem in scored[:top_k]]


def _cosine_similarity(a: list, b: list) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)
