"""
meta_builder.py — generates a complete N-agent simulation system from one
theme prompt, instead of hand-writing personas like we did for the town sim.

How it works (a real, small mesh in itself):
1. Splits the target agent count into batches (e.g. 30 agents -> 6 batches
   of 5), and runs one LLM call per batch IN PARALLEL (ThreadPoolExecutor,
   same primitive as agent.py's fan_out) — each call generates a handful of
   distinct personas for the given theme.
2. Merges all batches into one agents.json.
3. Writes out memory.py and tick_engine.py, adapted from the town sim's
   design but generalized — no hardcoded Japanese-town specifics, works
   for whatever theme you give it.

Usage:
    python3 -c "from meta_builder import build_agent_system; build_agent_system('a hospital emergency room', 30)"
"""

import json
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed

from provider_pool import ask_ai

BATCH_SIZE = 5
MAX_TOKENS_PER_BATCH = 3000


def _persona_prompt(theme, n, existing_names):
    avoid = f" Do not reuse these names: {', '.join(existing_names)}." if existing_names else ""
    return f"""Generate exactly {n} distinct characters for an agent-based simulation themed around: {theme}.

Each character needs these fields: id (short lowercase snake_case), name, role, \
personality (short comma-separated traits), backstory (1-2 sentences), \
routine (a dict of time-range strings like "6-9" to short activity descriptions, \
covering a full day), relationships (a dict of other character ids/names to a short \
relationship description — can reference characters from earlier batches by name \
if it makes sense, otherwise leave empty), secret (a private goal or hidden truth \
that could drive an interesting story).{avoid}

Respond with ONLY a JSON array of {n} objects, no markdown fences, no commentary, \
no explanation before or after. Just the raw JSON array."""


def _extract_json_array(text):
    """Models sometimes wrap JSON in markdown fences despite instructions —
    strip those before parsing."""
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return json.loads(text)


def _generate_batch(theme, n, existing_names):
    prompt = _persona_prompt(theme, n, existing_names)
    message = ask_ai([{"role": "user", "content": prompt}], max_tokens=MAX_TOKENS_PER_BATCH)

    if isinstance(message, dict) and "error" in message:
        return [], f"Batch failed: {message['error']}"

    content = message.get("content") if isinstance(message, dict) else message.content
    try:
        agents = _extract_json_array(content)
        if not isinstance(agents, list):
            return [], f"Batch did not return a JSON array: {content[:200]}"
        return agents, None
    except (json.JSONDecodeError, TypeError) as e:
        return [], f"Batch JSON parse failed ({e}): {content[:200]}"


def generate_roster(theme, count=30, batch_size=BATCH_SIZE, max_workers=6):
    """
    Generates `count` personas for `theme`, in parallel batches.
    Returns (agents_list, errors_list) — errors_list is non-empty if any
    batch failed, but successful batches are still returned so a partial
    roster isn't wasted.
    """
    batches = []
    remaining = count
    while remaining > 0:
        n = min(batch_size, remaining)
        batches.append(n)
        remaining -= n

    all_agents = []
    errors = []

    # First batch runs alone so later batches can reference its names and
    # avoid duplicates; remaining batches run in parallel against each other.
    first_n = batches[0]
    first_agents, err = _generate_batch(theme, first_n, [])
    all_agents.extend(first_agents)
    if err:
        errors.append(err)

    if len(batches) > 1:
        existing_names = [a.get("name", "") for a in all_agents]
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(_generate_batch, theme, n, existing_names): n
                for n in batches[1:]
            }
            for future in as_completed(futures):
                agents, err = future.result()
                all_agents.extend(agents)
                if err:
                    errors.append(err)

    return all_agents, errors


TICK_ENGINE_TEMPLATE = '''"""
tick_engine.py — generated by meta_builder.py for theme: {theme}

Advances simulated time and generates each agent's next action via LLM,
same pattern as the original town sim: personality + routine + relevant
memories -> one action per tick -> logged and remembered.

Run with: python tick_engine.py
Requires an API key set via environment variable (see provider_pool.py).
"""

import json
import time
import os

from memory import AgentMemoryStore
from provider_pool import ask_ai

TICK_HOURS = list(range(24))
EVENT_LOG_PATH = "event_log.json"
AGENTS_PATH = "agents.json"


def load_agents():
    with open(AGENTS_PATH, "r") as f:
        return json.load(f)["agents"]


def routine_for_hour(agent, hour):
    routine = agent.get("routine", {{}})
    for time_range, activity in routine.items():
        if time_range == "variable":
            continue
        if "-" in time_range:
            start, end = time_range.split("-")
            start, end = int(start), int(end)
            if start < end:
                if start <= hour < end:
                    return activity
            else:
                if hour >= start or hour < end:
                    return activity
    return routine.get("variable", "No specific plan this hour.")


def build_prompt(agent, hour, day, memories):
    memory_text = "\\n".join(f"- {{m.text}}" for m in memories) if memories else "No notable memories yet."
    relationships = "\\n".join(f"- {{name}}: {{desc}}" for name, desc in agent.get("relationships", {{}}).items())

    return f"""You are {{agent['name']}}, {{agent['role']}} in a simulation themed: {theme}.

Personality: {{agent['personality']}}
Backstory: {{agent.get('backstory', '')}}
Private goal/secret (quietly influences you, never state outright unless it truly fits): {{agent.get('secret', 'None')}}

Current time: Day {{day}}, Hour {{hour}}:00
Your usual routine at this hour: {{routine_for_hour(agent, hour)}}

Relationships:
{{relationships or 'No notable relationships defined.'}}

Relevant memories:
{{memory_text}}

What do you do or say right now? Respond in 1-3 sentences, third person,
as a short story beat. Include dialogue in quotes if you speak to someone.
Stay strictly in character. Do not narrate for other agents, only {{agent['name']}}.
"""


def call_llm(prompt):
    message = ask_ai([{{"role": "user", "content": prompt}}])
    if isinstance(message, dict) and "error" in message:
        return f"[ERROR] {{message['error']}}"
    content = message.get("content") if isinstance(message, dict) else message.content
    return (content or "").strip()


def log_event(day, hour, agent_name, action_text):
    entry = {{"day": day, "hour": hour, "agent": agent_name, "text": action_text, "logged_at": time.time()}}
    log = []
    if os.path.exists(EVENT_LOG_PATH):
        with open(EVENT_LOG_PATH, "r") as f:
            log = json.load(f)
    log.append(entry)
    with open(EVENT_LOG_PATH, "w") as f:
        json.dump(log, f, indent=2)
    print(f"[Day {{day}} {{hour:02d}}:00] {{agent_name}}: {{action_text}}")


def run_tick(day, hour, agents, stores):
    global_tick = day * 24 + hour
    for agent in agents:
        store = stores[agent["id"]]
        memories = store.retrieve_relevant(current_tick=global_tick, top_k=5)
        prompt = build_prompt(agent, hour, day, memories)
        action_text = call_llm(prompt)
        log_event(day, hour, agent["name"], action_text)
        store.add(text=action_text, tick=global_tick, importance=5)


def main():
    agents = load_agents()
    stores = {{a["id"]: AgentMemoryStore(a["id"]) for a in agents}}
    day = 0
    while True:
        for hour in TICK_HOURS:
            run_tick(day, hour, agents, stores)
            time.sleep(1)
        day += 1


if __name__ == "__main__":
    main()
'''


MEMORY_TEMPLATE = '''"""
memory.py — per-agent memory storage, generated by meta_builder.py.

Same design as the original town sim: recency + importance + relevance
blended for retrieval. No embeddings needed here — cheap and good enough
for a tick-based simulation where "importance" already does most of the
work of surfacing what matters.
"""

import json
import math
import os
import time
from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass
class Memory:
    text: str
    tick: int
    importance: int = 5
    embedding: Optional[list] = None
    created_at: float = field(default_factory=time.time)


class AgentMemoryStore:
    def __init__(self, agent_id: str, storage_dir: str = "memories"):
        self.agent_id = agent_id
        self.storage_dir = storage_dir
        os.makedirs(storage_dir, exist_ok=True)
        self.path = os.path.join(storage_dir, f"{agent_id}.json")
        self.memories: list[Memory] = self._load()

    def _load(self) -> list[Memory]:
        if not os.path.exists(self.path):
            return []
        with open(self.path, "r") as f:
            raw = json.load(f)
        return [Memory(**m) for m in raw]

    def save(self):
        with open(self.path, "w") as f:
            json.dump([asdict(m) for m in self.memories], f, indent=2)

    def add(self, text: str, tick: int, importance: int = 5, embedding=None):
        mem = Memory(text=text, tick=tick, importance=importance, embedding=embedding)
        self.memories.append(mem)
        self.save()
        return mem

    def retrieve_relevant(self, current_tick: int, query_embedding=None, top_k: int = 5):
        if not self.memories:
            return []
        scored = []
        for mem in self.memories:
            recency_score = math.exp(-0.01 * max(0, current_tick - mem.tick))
            importance_score = mem.importance / 10.0
            relevance_score = 0.5
            if query_embedding is not None and mem.embedding is not None:
                relevance_score = _cosine_similarity(query_embedding, mem.embedding)
            total = recency_score + importance_score + relevance_score
            scored.append((total, mem))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [mem for _, mem in scored[:top_k]]


def _cosine_similarity(a: list, b: list) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)
'''

VIEWER_TEMPLATE = '''"""
viewer.py — live feed viewer, generated by meta_builder.py for theme: {theme}

Run alongside tick_engine.py in a separate shell:
    python viewer.py
Then open the web preview Replit gives you.
"""

import json
import os
from flask import Flask, render_template_string

app = Flask(__name__)
EVENT_LOG_PATH = "event_log.json"

TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>{theme} — Live Feed</title>
    <meta http-equiv="refresh" content="5">
    <style>
        body {{ font-family: Georgia, serif; background: #14181f; color: #e8e8e8; max-width: 700px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ color: #7fb4e0; border-bottom: 1px solid #333; padding-bottom: 10px; }}
        .event {{ margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid #222; }}
        .meta {{ color: #888; font-size: 0.85em; margin-bottom: 4px; }}
        .agent {{ color: #7fb4e0; font-weight: bold; }}
        .worldevent {{ color: #e0a860; font-weight: bold; }}
    </style>
</head>
<body>
    <h1>{theme} — Live Feed</h1>
    {{% for e in events %}}
    <div class="event">
        <div class="meta">Day {{{{ e.day }}}}, {{{{ "%02d"|format(e.hour) }}}}:00</div>
        {{% if e.agent == "WORLD EVENT" %}}
        <div class="worldevent">🌐 {{{{ e.text }}}}</div>
        {{% else %}}
        <div><span class="agent">{{{{ e.agent }}}}</span> — {{{{ e.text }}}}</div>
        {{% endif %}}
    </div>
    {{% endfor %}}
</body>
</html>
"""


@app.route("/")
def feed():
    events = []
    if os.path.exists(EVENT_LOG_PATH):
        with open(EVENT_LOG_PATH, "r") as f:
            events = json.load(f)
    events = list(reversed(events))[:100]
    return render_template_string(TEMPLATE, events=events)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
'''


def build_agent_system(theme, count=30, output_dir="."):
    """
    Generates a FULL, self-contained N-agent system for `theme` — no manual
    follow-up files needed:
    - agents.json (the roster, built via parallel batch generation)
    - memory.py (per-agent memory storage, theme-independent, always correct)
    - tick_engine.py (the tick loop, themed)
    - viewer.py (live web feed, themed)

    Returns a summary string. If some batches failed, the roster will have
    fewer than `count` agents and the summary will say so honestly rather
    than silently returning a partial result.
    """
    agents, errors = generate_roster(theme, count)

    os.makedirs(output_dir, exist_ok=True)

    agents_path = os.path.join(output_dir, "agents.json")
    with open(agents_path, "w") as f:
        json.dump({"agents": agents}, f, indent=2)

    memory_path = os.path.join(output_dir, "memory.py")
    with open(memory_path, "w") as f:
        f.write(MEMORY_TEMPLATE)

    tick_engine_path = os.path.join(output_dir, "tick_engine.py")
    with open(tick_engine_path, "w") as f:
        f.write(TICK_ENGINE_TEMPLATE.format(theme=theme))

    viewer_path = os.path.join(output_dir, "viewer.py")
    with open(viewer_path, "w") as f:
        f.write(VIEWER_TEMPLATE.format(theme=theme))

    summary = f"Generated {len(agents)}/{count} agents for theme: '{theme}'\n"
    summary += f"Wrote: {agents_path}, {memory_path}, {tick_engine_path}, {viewer_path}\n"
    summary += "Fully self-contained — run `python tick_engine.py` and `python viewer.py` in separate shells.\n"
    if errors:
        summary += f"\n{len(errors)} batch(es) had issues:\n" + "\n".join(f"  - {e}" for e in errors)
    return summary
