"""
tick_engine.py — generated by meta_builder.py for theme: a small coffee shop with a barista, the owner, a regular customer, a delivery driver, and a rival cafe owner secretly trying to poach the regular

Advances simulated time and generates each agent's next action via LLM,
same pattern as the original town sim: personality + routine + relevant
memories -> one action per tick -> logged and remembered.

Run with: python tick_engine.py
Requires an API key set via environment variable (see provider_pool.py).
"""

import json
import time
import os

from memory import AgentMemoryStore
from provider_pool import ask_ai

TICK_HOURS = list(range(24))
EVENT_LOG_PATH = "event_log.json"
AGENTS_PATH = "agents.json"


def load_agents():
    with open(AGENTS_PATH, "r") as f:
        return json.load(f)["agents"]


def routine_for_hour(agent, hour):
    routine = agent.get("routine", {})
    for time_range, activity in routine.items():
        if time_range == "variable":
            continue
        if "-" in time_range:
            start, end = time_range.split("-")
            start, end = int(start), int(end)
            if start < end:
                if start <= hour < end:
                    return activity
            else:
                if hour >= start or hour < end:
                    return activity
    return routine.get("variable", "No specific plan this hour.")


def build_prompt(agent, hour, day, memories):
    memory_text = "\n".join(f"- {m.text}" for m in memories) if memories else "No notable memories yet."
    relationships = "\n".join(f"- {name}: {desc}" for name, desc in agent.get("relationships", {}).items())

    return f"""You are {agent['name']}, {agent['role']} in a simulation themed: a small coffee shop with a barista, the owner, a regular customer, a delivery driver, and a rival cafe owner secretly trying to poach the regular.

Personality: {agent['personality']}
Backstory: {agent.get('backstory', '')}
Private goal/secret (quietly influences you, never state outright unless it truly fits): {agent.get('secret', 'None')}

Current time: Day {day}, Hour {hour}:00
Your usual routine at this hour: {routine_for_hour(agent, hour)}

Relationships:
{relationships or 'No notable relationships defined.'}

Relevant memories:
{memory_text}

What do you do or say right now? Respond in 1-3 sentences, third person,
as a short story beat. Include dialogue in quotes if you speak to someone.
Stay strictly in character. Do not narrate for other agents, only {agent['name']}.
"""


def call_llm(prompt):
    message = ask_ai([{"role": "user", "content": prompt}])
    if isinstance(message, dict) and "error" in message:
        return f"[ERROR] {message['error']}"
    content = message.get("content") if isinstance(message, dict) else message.content
    return (content or "").strip()


def log_event(day, hour, agent_name, action_text):
    entry = {"day": day, "hour": hour, "agent": agent_name, "text": action_text, "logged_at": time.time()}
    log = []
    if os.path.exists(EVENT_LOG_PATH):
        with open(EVENT_LOG_PATH, "r") as f:
            log = json.load(f)
    log.append(entry)
    with open(EVENT_LOG_PATH, "w") as f:
        json.dump(log, f, indent=2)
    print(f"[Day {day} {hour:02d}:00] {agent_name}: {action_text}")


def run_tick(day, hour, agents, stores):
    global_tick = day * 24 + hour
    for agent in agents:
        store = stores[agent["id"]]
        memories = store.retrieve_relevant(current_tick=global_tick, top_k=5)
        prompt = build_prompt(agent, hour, day, memories)
        action_text = call_llm(prompt)
        log_event(day, hour, agent["name"], action_text)
        store.add(text=action_text, tick=global_tick, importance=5)


def main():
    agents = load_agents()
    stores = {a["id"]: AgentMemoryStore(a["id"]) for a in agents}
    day = 0
    while True:
        for hour in TICK_HOURS:
            run_tick(day, hour, agents, stores)
            time.sleep(1)
        day += 1


if __name__ == "__main__":
    main()
