"""
viewer.py — live feed viewer, generated by meta_builder.py for theme: a small coffee shop with a barista, the owner, a regular customer, a delivery driver, and a rival cafe owner secretly trying to poach the regular

Run alongside tick_engine.py in a separate shell:
    python viewer.py
Then open the web preview Replit gives you.
"""

import json
import os
from flask import Flask, render_template_string

app = Flask(__name__)
EVENT_LOG_PATH = "event_log.json"

TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>a small coffee shop with a barista, the owner, a regular customer, a delivery driver, and a rival cafe owner secretly trying to poach the regular — Live Feed</title>
    <meta http-equiv="refresh" content="5">
    <style>
        body { font-family: Georgia, serif; background: #14181f; color: #e8e8e8; max-width: 700px; margin: 40px auto; padding: 0 20px; }
        h1 { color: #7fb4e0; border-bottom: 1px solid #333; padding-bottom: 10px; }
        .event { margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid #222; }
        .meta { color: #888; font-size: 0.85em; margin-bottom: 4px; }
        .agent { color: #7fb4e0; font-weight: bold; }
        .worldevent { color: #e0a860; font-weight: bold; }
    </style>
</head>
<body>
    <h1>a small coffee shop with a barista, the owner, a regular customer, a delivery driver, and a rival cafe owner secretly trying to poach the regular — Live Feed</h1>
    {% for e in events %}
    <div class="event">
        <div class="meta">Day {{ e.day }}, {{ "%02d"|format(e.hour) }}:00</div>
        {% if e.agent == "WORLD EVENT" %}
        <div class="worldevent">🌐 {{ e.text }}</div>
        {% else %}
        <div><span class="agent">{{ e.agent }}</span> — {{ e.text }}</div>
        {% endif %}
    </div>
    {% endfor %}
</body>
</html>
"""


@app.route("/")
def feed():
    events = []
    if os.path.exists(EVENT_LOG_PATH):
        with open(EVENT_LOG_PATH, "r") as f:
            events = json.load(f)
    events = list(reversed(events))[:100]
    return render_template_string(TEMPLATE, events=events)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
